name: Run Image Processing Tests

on:
  push:
    branches: [ "main" ]  # Sproži delovni tok ob vsakem pushu v vejo 'main'.

jobs:
  setup_environment:  # Definira delo za nastavitev okolja.
    runs-on: self-hosted  # Določa, da bo delo tekel na samohostovanem runnerju.
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ]  # Določa matriko za testiranje z več verzijami Pythona.
    steps:
      - uses: actions/checkout@v2  # Pridobi kodo repozitorija.
      - name: Set up Python
        uses: actions/setup-python@v2  # Nastavi Python okolje z določeno verzijo.
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-glx  # Namesti sistemsko odvisnost potrebno za teste.
      - name: Install Python dependencies and redirect errors
        run: |
          python -m pip install --upgrade pip && pip install opencv-python numpy 2> napaka.txt  # Nadgradi pip in namesti potrebne Python pakete; preusmeri morebitne napake v datoteko 'napaka.txt'.
      - name: Upload error log if exists and not empty
        uses: actions/upload-artifact@v4  # Naloži dnevnik napak kot artefakt, če obstaja in ni prazen.
        if: always()  # Izvedi korak ne glede na rezultat prejšnjih korakov.
        with:
          name: error-report-py${{ matrix.python-version }}
          path: napaka.txt

  run_tests:  # Definira delo za izvajanje testov.
    needs: setup_environment  # Določa, da se to delo začne šele, ko se 'setup_environment' uspešno zaključi.
    runs-on: self-hosted  # Ponovno, določa samohostovani runner.
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ]  # Podobno, uporablja matriko za več verzij Pythona.
    steps:
      - uses: actions/checkout@v2  # Ponovno pridobi kodo repozitorija.
      - uses: actions/setup-python@v2  # Nastavi Python okolje.
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v4  # Prenese artefakte, v tem primeru dnevnike napak iz prejšnjega dela, če obstajajo.
        with:
          name: error-report-py${{ matrix.python-version }}
      - name: Check for error report
        run: |
          if [ -s napaka.txt ]; then
            echo "Errors were detected in the setup environment."
            cat napaka.txt
            exit 1
          fi  # Preveri, če obstajajo napake v 'napaka.txt' in, če ja, izpiše napake in prekine delovni tok.
      - name: Run image processing tests
        run: python test_obdelave_slike.py  # Izvede teste za obdelavo slik.