name: Run Image Processing Tests

on:
  push:
    branches: [ "main" ]

jobs:
  setup_environment:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ '3.9' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-glx
      - name: Install Python dependencies and redirect errors
        run: |
          python -m pip install --upgrade pip && pip install opencv-python numpy 2> napaka.txt
      - name: Upload error log if exists and not empty
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: error-report-py${{ matrix.python-version }}
          path: napaka.txt

  run_tests:
    needs: setup_environment
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v4
        with:
          name: error-report-py${{ matrix.python-version }}
      - name: Check for error report
        run: |
          if [ -s napaka.txt ]; then
            echo "Errors were detected in the setup environment."
            cat napaka.txt
            exit 1
          fi
      - name: Run image processing tests
        run: python test_obdelave_slike.py
